# Generated by Django 5.0.6 on 2024-07-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_article_author_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_article_status', 'менять статус статье')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
